project:
  type: website

website:
  title: "AD688 Employability - Group 2"
  navbar:
    background: "#A8B5A2"      
    foreground: "#ffffff"      
    left:
      - href: tabs/index.qmd
        text: "Home"
      - href: tabs/team_analysis.qmd
        text: "Research"
      - href: tabs/data_analysis.ipynb
        text: "Data Analysis"
      - href: tabs/career_plan.qmd
        text: "Career Plan"
      - href: tabs/about.qmd
        text: "About"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    mainfont: "Helvetica Neue, Lato, sans-serif"
    linkcolor: "#78997F"
    backgroundcolor: "#F8F9F8"
    code-block-bg: "#F3F5F3"

