project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    background: "#A8B5A2"
    foreground: "#ffffff"
    left:
      - href: tabs/index.qmd
        text: "Home"
      - href: tabs/introduction.qmd
        text: "Introduction"
      - href: tabs/data_cleaning.ipynb
        text: "Data Cleaning"
      - href: tabs/eda.ipynb
        text: "Exploratory Data Analysis"
      - href: tabs/skill_gap_analysis.ipynb
        text: "Skill Gap Analysis"
      - href: tabs/ml_methods.ipynb
        text: "ML Methods"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    mainfont: "Helvetica Neue, Lato, sans-serif"
    linkcolor: "#78997F"
    backgroundcolor: "#F8F0F8"
    code-block-bg: "#F3F5F3"

execute:
  enabled: false
  cache: false
  freeze: false
  keep-md: false
  execute-dir: project